---
include:
  - board: eyelash_sofle_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    artifact-name: eyelash_sofle_left
  - board: eyelash_sofle_right
    shield: nice_view_gem
    artifact-name: eyelash_sofle_right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
